import React from 'react';
import {
   Button,
   Col,
   Form,
   Input,
   Row,
   Table,
   Typography
} from 'antd';

const columns = [
   {
      title: 'Time',
      dataIndex: 'time',
      key: 'time'
   },
   {
      title: 'Action',
      dataIndex: 'action',
      key: 'action'
   },
   {
      title: 'IP',
      dataIndex: 'ip',
      key: 'ip'
   },
];

const data = [
   {
      key: '1',
      time: 'You have not made any changes'
   }
];

export default function Security() {
   const [form] = Form.useForm();

   const onFinish = (values) => {
      console.log('Received values of form: ', values);
   };

   return (
      <Row>
         <Col xs={24} style={{ marginBottom: '20px' }}>
            <Form
               form={form}
               layout='vertical'
               onFinish={onFinish}
            >
               <Col xs={24} md={8}>
                  <Form.Item
                     name="email"
                     label="Email"
                     rules={[{ type: 'email' }]}
                  >
                     <Input />
                  </Form.Item>

                  <Form.Item
                     name="phone"
                     label="Phone Number"
                  >
                     <Input />
                  </Form.Item>
               </Col>
            </Form>
         </Col>

         <Col xs={24}>
            <Typography.Title level={3}>Security</Typography.Title>
         </Col>

         <Col xs={24}>
            <Typography.Title level={4}>2-Factor Authentication</Typography.Title>
         </Col>

         <Col xs={24} sm={12} style={{ marginBottom: '20px' }}>
            <Typography.Text
            > Setting up 2-Factor Authentication (2FA) provides an additional of security to your Crypto.com NFT account. With 2FA enabled, you will have to provide the code generated by your authenticator app to perform certain actions on the platform
            </Typography.Text>
         </Col>

         <Col xs={24} style={{ marginBottom: '30px' }} >
            <Form
               form={form}
            >
               <Form.Item style={{ margin: '0px' }}>
                  <Button
                     htmlType='submit'
                     style={{
                        backgroundImage: 'linear-gradient(to right, #3A9EF5 , #1DC9F5)',
                        color: '#fff',
                        borderRadius: '5px',
                        border: 'none',
                        width: '110px',
                        height: '40px'
                     }}
                  >
                     Set Up 2FA
                  </Button>
               </Form.Item>
            </Form>
         </Col>

         <Col xs={24} >
            <Typography.Title level={4}>Security Settings History</Typography.Title>
         </Col>

         <Col xs={24} sm={12} >
            <Table
               columns={columns}
               dataSource={data}
               pagination={false}
               size='small'
               bordered={true}
            />
         </Col>

      </Row>
   )
};
